### ISSUE TITLE
T3: Tree Transducer Toolkit link broken

### ISSUE THREAD

**Issue by zhyanlin** [alexrudnick/wiki#15]
Hi,
The T3 download link is broken. I tried to find a source code of it by myself, but failed. Could you provide a method to get a copy? Thanks a lot.

**Comment by alexrudnick** [comment]
Hi, this is a bunch of random semi-organized notes that I put together during my doctoral work.

I did make a tree transducer toolkit, here: https://github.com/alexrudnick/kurt

... but it's certainly not ready for anybody to use seriously. Just a small academic project. Feel free to play with it, but no guarantees that it will work for your use case.
